name: movie
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  cupertino_icons: ^1.0.6
  dot_curved_bottom_nav: ^0.0.2
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    -  assets/images/logo.png
    -  assets/images/fav.png
    -  assets/images/insideout.png
    -  assets/images/satu.png
    -  assets/images/dua.png
    -  assets/images/tiga.png
    -  assets/images/empat.png
    -  assets/images/lima.png
    -  assets/images/enam.png
    -  assets/images/tujuh.png
    -  assets/images/lapan.png
    -  assets/images/sembilan.png
